services:

  workspace:
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
    working_dir: /var/www/laravel
    volumes:
      - ../:/var/www/laravel
      - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
      - ./php-fpm/xphp.ini:/usr/local/etc/php/conf.d/xphp.ini:ro
    ports:
      - "${PHP_PORT}:9000"
      - "${VITE_PORT}:5173"
      - "${WEBSOCKET_PORT}:6001"
    tty: true
    networks:
      - laravel-network
    depends_on:
      redis:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: ${NGINX_IMAGE}
    volumes:
      - ../:/var/www/laravel:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      #- ./nginx/error.log:/var/log/nginx/error.log
      #- ./nginx/access.log:/var/log/nginx/access.log
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - workspace
    networks:
      - laravel-network

  redis:
    image: ${REDIS_IMAGE}
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  redis-data:
